x-veld:
    veld_executable:
        input:
            path: "/veld/input/"
            type: "custom"
            description: "This input is hard-wired to the apis spacy-ner repo and not made for generic usage."
        output:
            path: "/veld/output/"
            type: "md"
            description: "evaluation report of the models from the apis spacy-ner repo."

services:
    veld:
        build: .
        volumes:
            - ./:/veld/executable/

